version: '3.8'

services:
  node-20:
    image: node:20

  test-npm-package:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: test-npm-package
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 85:5055
    volumes:
      - ./:/pkg
    tty: true
    stdin_open: true
    restart: on-failure
